steps:

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/albion-sheets:$COMMIT_SHA', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/albion-sheets:$COMMIT_SHA']

  - name: 'gcr.io/google.com/cloudsdktool/gcloud'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'albion-sheets'
      - '--image=gcr.io/$PROJECT_ID/albion-sheets:$COMMIT_SHA'
      - '--region=southamerica-east1'
      - '--platform=managed'
      - '--service-account=albion-sheets@albion-teste.iam.gserviceaccount.com'
      - '--set-env-vars=GCP_PROJECT_ID=$PROJECT_ID,GCS_BUCKET_NAME=albion-data,BIGQUERY_DATASET=albion_data'

images:
  - 'gcr.io/$PROJECT_ID/albion-sheets:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY